### ISSUE TITLE
infografia 

### ISSUE THREAD

**Issue by christopheremv** [SistemasTecTlaxiaco/infografia-christopheremv#2]
[infografia ciclo.pdf](https://github.com/SistemasTecTlaxiaco/infografia-christopheremv/files/7126176/infografia.ciclo.pdf)

**Comment by IsraelNicolas61** [comment]
¡Buen trabajo!
Calificación 18/20 puntos

**Comment by josealfredo79** [comment]
esta bien hecho y revisado.
